import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { Circle } from '@/lib/models';
import { computeScore } from '@/lib/creditEngine';
import { requireAuth, unauthorized } from '@/lib/apiAuth';

// GET /api/circles — list user's circles
export async function GET(req: NextRequest) {
  const auth = requireAuth(req);
  if (!auth) return unauthorized();
  await connectDB();

  const { searchParams } = new URL(req.url);
  const query = searchParams.get('q');
  const uci = searchParams.get('uci');

  const formatCircle = (c: any) => {
    const obj = c.toObject();
    obj.id = obj._id.toString();
    delete obj._id;
    return obj;
  };

  // Search mode: by name or UCI
  if (query || uci) {
    const filter: any = {};
    if (uci) {
      filter.uci = uci.trim().toUpperCase();
    } else if (query) {
      filter.name = { $regex: query.trim(), $options: 'i' };
      filter.isPublic = true;
    }
    const results = await Circle.find(filter).limit(20);
    return NextResponse.json(results.map(formatCircle));
  }

  // Default: user's circles
  const circles = await Circle.find({ members: auth.pubKey });
  return NextResponse.json(circles.map(formatCircle));
}

// POST /api/circles — create a circle
export async function POST(req: NextRequest) {
  const auth = requireAuth(req);
  if (!auth) return unauthorized();

  const { name, description, isPublic, circleRules, socialLink } = await req.json();
  if (!name || !name.trim()) return NextResponse.json({ error: 'Circle name is required' }, { status: 400 });

  await connectDB();

  const circle = await Circle.create({
    name: name.trim(),
    description: description?.trim() || '',
    circleRules: circleRules?.trim() || '',
    socialLink: socialLink?.trim() || '',
    isPublic: isPublic !== false,
    creatorId: auth.pubKey,
    members: [auth.pubKey],
    pendingJoinRequests: [],
    status: 'ACTIVE',
    inviteCode: Math.random().toString(36).slice(2, 10).toUpperCase(),
    borrowApprovalEnabled: false,
    // uci is auto-generated by model default
  });

  computeScore(auth.pubKey).catch(console.error);

  const formatted = circle.toObject();
  formatted.id = formatted._id.toString();
  delete formatted._id;

  return NextResponse.json(formatted, { status: 201 });
}
